"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const order_controllers_1 = require("../controllers/order.controllers");
const router = (0, express_1.Router)();
router.post('/', order_controllers_1.OrderControllers.create);
router.get('/', order_controllers_1.OrderControllers.getAll);
router.get('/:id', order_controllers_1.OrderControllers.getById);
// router.put('/:id', AuthorsController.updateOne);
router.delete('/:id', order_controllers_1.OrderControllers.delete);
exports.default = router;
